
package com.terry.cxfserver.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.terry.cxfserver.service.impl.WSDLBookService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-18T15:54:14.874+09:00
 * Generated source version: 3.2.5
 *
 */
public final class WSDLService_WSDLBookServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.service.cxfserver.terry.com/", "WSDLBookService");

    private WSDLService_WSDLBookServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WSDLBookService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        WSDLBookService ss = new WSDLBookService(wsdlURL, SERVICE_NAME);
        WSDLService port = ss.getWSDLBookServiceImplPort();

        {
        System.out.println("Invoking view...");
        java.lang.Integer _view_key = Integer.valueOf(2124665678);
        book.dto.cxfserver.terry.com.Book _view__return = port.view(_view_key);
        System.out.println("view.result=" + _view__return);


        }
        {
        System.out.println("Invoking getList...");
        java.util.List<book.dto.cxfserver.terry.com.Book> _getList__return = port.getList();
        System.out.println("getList.result=" + _getList__return);


        }

        System.exit(0);
    }

}
