package com.terry.cxfserver.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-18T15:54:14.931+09:00
 * Generated source version: 3.2.5
 *
 */
@WebService(targetNamespace = "http://service.cxfserver.terry.com/", name = "WSDLService")
@XmlSeeAlso({ObjectFactory.class, book.dto.cxfserver.terry.com.ObjectFactory.class})
public interface WSDLService {

    @WebMethod
    @RequestWrapper(localName = "view", targetNamespace = "http://service.cxfserver.terry.com/", className = "com.terry.cxfserver.service.View")
    @ResponseWrapper(localName = "viewResponse", targetNamespace = "http://service.cxfserver.terry.com/", className = "com.terry.cxfserver.service.ViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public book.dto.cxfserver.terry.com.Book view(
        @WebParam(name = "key", targetNamespace = "")
        java.lang.Integer key
    );

    @WebMethod
    @RequestWrapper(localName = "getList", targetNamespace = "http://service.cxfserver.terry.com/", className = "com.terry.cxfserver.service.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.cxfserver.terry.com/", className = "com.terry.cxfserver.service.GetListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<book.dto.cxfserver.terry.com.Book> getList();
}
