package com.terry.cxfserver.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.terry.cxfserver.service.WSDLService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.5
 * 2018-07-18T15:54:14.936+09:00
 * Generated source version: 3.2.5
 *
 */
@WebServiceClient(name = "WSDLBookService",
                  wsdlLocation = "http://localhost:8080/cxf/WSDLBookService?wsdl",
                  targetNamespace = "http://impl.service.cxfserver.terry.com/")
public class WSDLBookService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.cxfserver.terry.com/", "WSDLBookService");
    public final static QName WSDLBookServiceImplPort = new QName("http://impl.service.cxfserver.terry.com/", "WSDLBookServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf/WSDLBookService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSDLBookService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf/WSDLBookService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSDLBookService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSDLBookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSDLBookService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public WSDLBookService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WSDLBookService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WSDLBookService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns WSDLService
     */
    @WebEndpoint(name = "WSDLBookServiceImplPort")
    public WSDLService getWSDLBookServiceImplPort() {
        return super.getPort(WSDLBookServiceImplPort, WSDLService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSDLService
     */
    @WebEndpoint(name = "WSDLBookServiceImplPort")
    public WSDLService getWSDLBookServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WSDLBookServiceImplPort, WSDLService.class, features);
    }

}
